# Generated by Django 3.0.4 on 2020-07-17 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='customer',
            new_name='custome',
        ),
    ]
